/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Statistics;

import DataManipulation.Rounding;
import Printing.Printsupport;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author manual-pc
 */
public class DayEndView extends javax.swing.JFrame {

    /**
     * Creates new form DayEndView
     */
    DayEndReport report = DayEndReport.getInstance();
    
    public DayEndView() {
        initComponents();
        
        generateReport();
//        String date = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        partPayments_panel = new javax.swing.JPanel();
        partpayments_lbl = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        sales_panel = new javax.swing.JPanel();
        total_sales_lbl = new javax.swing.JLabel();
        credit_sales_lbl = new javax.swing.JLabel();
        cash_sales_lbl = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        halfpayments_lbl = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        total_cashSale_lbl = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        returns_panel = new javax.swing.JPanel();
        total_returns_lbl = new javax.swing.JLabel();
        credit_returns_lbl = new javax.swing.JLabel();
        cash_returns_lbl = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        datepicker = new com.toedter.calendar.JDateChooser();
        refresh_btn = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Day End Report");

        partPayments_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Part Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        partpayments_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        partpayments_lbl.setText("xxxxx.xx");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Part Payments");

        javax.swing.GroupLayout partPayments_panelLayout = new javax.swing.GroupLayout(partPayments_panel);
        partPayments_panel.setLayout(partPayments_panelLayout);
        partPayments_panelLayout.setHorizontalGroup(
            partPayments_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partPayments_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(partpayments_lbl)
                .addGap(23, 23, 23))
        );
        partPayments_panelLayout.setVerticalGroup(
            partPayments_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partPayments_panelLayout.createSequentialGroup()
                .addGroup(partPayments_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(partPayments_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(partpayments_lbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, partPayments_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        sales_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        total_sales_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_sales_lbl.setText("xxxxx.xx");

        credit_sales_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        credit_sales_lbl.setText("xxxxx.xx");

        cash_sales_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cash_sales_lbl.setText("xxxxx.xx");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Cash Sales");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Credit Sales");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Half Payments");

        halfpayments_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        halfpayments_lbl.setText("xxxxx.xx");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("(");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText(")");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Total Cash Sales");

        total_cashSale_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_cashSale_lbl.setText("xxxxx.xx");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setText("Total Sales");

        javax.swing.GroupLayout sales_panelLayout = new javax.swing.GroupLayout(sales_panel);
        sales_panel.setLayout(sales_panelLayout);
        sales_panelLayout.setHorizontalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sales_panelLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(123, 123, 123)
                        .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sales_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(total_cashSale_lbl)
                                .addGap(17, 17, 17))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(sales_panelLayout.createSequentialGroup()
                        .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addGroup(sales_panelLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sales_panelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(halfpayments_lbl))
                            .addComponent(credit_sales_lbl, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cash_sales_lbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sales_panelLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(total_sales_lbl)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        sales_panelLayout.setVerticalGroup(
            sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sales_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cash_sales_lbl)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(credit_sales_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(halfpayments_lbl)
                    .addComponent(jLabel19)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_sales_lbl)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(sales_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_cashSale_lbl)
                    .addComponent(jLabel18))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        returns_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Returns", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        total_returns_lbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_returns_lbl.setText("xxxxx.xx");

        credit_returns_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        credit_returns_lbl.setText("xxxxx.xx");

        cash_returns_lbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cash_returns_lbl.setText("xxxxx.xx");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Cash Returns");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Credit Returns");

        javax.swing.GroupLayout returns_panelLayout = new javax.swing.GroupLayout(returns_panel);
        returns_panel.setLayout(returns_panelLayout);
        returns_panelLayout.setHorizontalGroup(
            returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returns_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returns_panelLayout.createSequentialGroup()
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returns_panelLayout.createSequentialGroup()
                        .addGroup(returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(credit_returns_lbl)
                            .addComponent(cash_returns_lbl))
                        .addGap(23, 23, 23))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returns_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total_returns_lbl)
                .addGap(22, 22, 22))
        );
        returns_panelLayout.setVerticalGroup(
            returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returns_panelLayout.createSequentialGroup()
                .addGroup(returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returns_panelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cash_returns_lbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returns_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(returns_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(credit_returns_lbl)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_returns_lbl)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        datepicker.setDateFormatString("yyyy-MM-dd");

        refresh_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-refresh-filled-50.png"))); // NOI18N
        refresh_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refresh_btnMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sales_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(refresh_btn)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(returns_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(partPayments_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(datepicker, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(refresh_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sales_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(returns_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partPayments_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refresh_btnMouseClicked
        Date date = datepicker.getDate();
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        report.setDate(df.format(date));
        generateReport();
    }//GEN-LAST:event_refresh_btnMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       printReport();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DayEndView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DayEndView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DayEndView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DayEndView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DayEndView().setVisible(true);
            }
        });
    }
    
    public void generateReport(){
        
        Date today = new Date();
        datepicker.setDate(today);
        
        boolean disposed = false;
        String cash_sale = report.getCashSales();
        if(!cash_sale.equals("null")){
            cash_sales_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(cash_sale)));
        }else{
            JOptionPane.showMessageDialog(null, "Sorry for this day can't prepare the day end report due to no sales");
            this.dispose();
            disposed = true;
        }
        
        if(!disposed){
            
            String credit_sales = report.getCreditSales();
            if (!credit_sales.equals("null")) {
                credit_sales_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(credit_sales)));
            } else {
                credit_sales_lbl.setText("0.00");
                credit_sales ="0.00";
            }

            String half_payments = report.getHalfPayments();
            if (!half_payments.equals("null")) {
                halfpayments_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(half_payments)));
            } else {
                halfpayments_lbl.setText("0.00");
                half_payments = "0.00";
            }

            double t_sales = Double.valueOf(cash_sale) + Double.valueOf(credit_sales);
            total_sales_lbl.setText(Rounding.decimalFormatiing(t_sales));

            double t_cash_sales = Double.valueOf(cash_sale) + Double.valueOf(half_payments);
            total_cashSale_lbl.setText(Rounding.decimalFormatiing(t_cash_sales));

            String cash_returns = report.getCashReturns();
            if (!cash_returns.equals("null")) {
                cash_returns_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(cash_returns)));
            } else {
                cash_returns_lbl.setText("0.00");
                cash_returns = "0.00";
            }

            String credit_retunrs = report.getCreditReturns();
            if (!credit_retunrs.equals("null")) {
                credit_returns_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(credit_retunrs)));
            } else {
                credit_returns_lbl.setText("0.00");
                credit_retunrs = "0.00";
            }

            double t_returns = Double.valueOf(cash_returns_lbl.getText()) + Double.valueOf(credit_returns_lbl.getText());
            if (t_returns != 0.00) {
                total_returns_lbl.setText(Rounding.decimalFormatiing(t_returns));
            } else {
                total_returns_lbl.setText("0.00");
            }

            String part_payments = report.getPartPayments();
            if (!part_payments.equals("null")) {
                partpayments_lbl.setText(Rounding.decimalFormatiing(Double.valueOf(part_payments)));
            } else {
                partpayments_lbl.setText("0.00");
                part_payments = "0.00";
            } 
        }
        
        
        
    }
    
   public void printReport(){
       Printsupport ps = new Printsupport();
       
       //Data setup to printing Information
       HashMap hm = new HashMap();
       hm.put("cash_sales",cash_sales_lbl.getText());
       hm.put("credit_sales",credit_sales_lbl.getText());
       hm.put("half_payments",halfpayments_lbl.getText());
       hm.put("total_sales",total_sales_lbl.getText());
       hm.put("total_cash_sales",total_cashSale_lbl.getText());
       hm.put("cash_returns",cash_returns_lbl.getText());
       hm.put("credit_returns",credit_returns_lbl.getText());
       hm.put("part_payments",partpayments_lbl.getText());
       
       ps.setMetaData(hm);
       
       
       PrinterJob pj = PrinterJob.getPrinterJob();

        pj.setPrintable(new Printsupport.DayEndPrintable(), ps.getCashPageFormat(pj));
        try {
            pj.print();

        } catch (PrinterException ex) {
            ex.printStackTrace();
        }
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cash_returns_lbl;
    private javax.swing.JLabel cash_sales_lbl;
    private javax.swing.JLabel credit_returns_lbl;
    private javax.swing.JLabel credit_sales_lbl;
    private com.toedter.calendar.JDateChooser datepicker;
    private javax.swing.JLabel halfpayments_lbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JPanel partPayments_panel;
    private javax.swing.JLabel partpayments_lbl;
    private javax.swing.JLabel refresh_btn;
    private javax.swing.JPanel returns_panel;
    private javax.swing.JPanel sales_panel;
    private javax.swing.JLabel total_cashSale_lbl;
    private javax.swing.JLabel total_returns_lbl;
    private javax.swing.JLabel total_sales_lbl;
    // End of variables declaration//GEN-END:variables
}
