/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import DBController.DataBaseConnector;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author manual-pc
 */


public class search_invoice extends javax.swing.JFrame {

    /**
     * Creates new form search_invoice
     */
    
    DataBaseConnector connector = null;
    static String invoiceID = null;
    
    public search_invoice(DataBaseConnector connector) {
        
        this.connector = connector;
        
        initComponents();
        
        AutoCompleteDecorator.decorate(search_date);
        AutoCompleteDecorator.decorate(search_userID);
        AutoCompleteDecorator.decorate(search_name);
        AutoCompleteDecorator.decorate(search_invoiceID);
        
        getRecords("users", "userID", search_userID);
        getRecords("users", "name", search_name);
        getRecords("orders", "orderID", search_invoiceID);
        getRecords("orders", "orderDate", search_date);
    }
    
    public void getRecords(String tableName,String coloumn,JComboBox combo){
        ArrayList list = new ArrayList();        
        list = connector.retreveDataColumn(tableName, coloumn);
       
        for (int i = 0; i < list.size(); i++) {
            combo.addItem(list.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_date = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        search_userID = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        search_name = new javax.swing.JComboBox<>();
        search_invoiceID = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search_date.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(search_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 180, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Date");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("userID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        search_userID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(search_userID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        search_name.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(search_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 30));

        search_invoiceID.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(search_invoiceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 120, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Invoice ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 210, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         invoiceID = String.valueOf(search_invoiceID.getSelectedItem());
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getInvoiceID(){
        
        return invoiceID;
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<String> search_date;
    private javax.swing.JComboBox<String> search_invoiceID;
    private javax.swing.JComboBox<String> search_name;
    private javax.swing.JComboBox<String> search_userID;
    // End of variables declaration//GEN-END:variables
}
