/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import DBController.DataBaseConnector;
import ViewManipulation.ViewManipulation;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author manual-pc
 */
public class Splash extends javax.swing.JFrame {

    /**
     * Creates new form Splash
     */
    DataBaseConnector connector = DataBaseConnector.getInstance();
    MainFrame mf;
    
    
    public Splash() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            connector.startConnection();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error in Connecting to database contact admin"+ex.getMessage());
            Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        base_panel = new javax.swing.JPanel();
        login_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user_name_txt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        login_cancel_btn = new javax.swing.JButton();
        user_password_txt = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        loading_panel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Login Form");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/settings.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 65));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 390));

        base_panel.setLayout(new java.awt.CardLayout());

        login_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(40, 53, 147));
        jLabel1.setText("Login Form");
        login_panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 16, -1, 42));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("UserName");
        login_panel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 107, 122, 42));

        user_name_txt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user_name_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_name_txtKeyPressed(evt);
            }
        });
        login_panel.add(user_name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 107, 183, 42));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N
        login_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 117, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/key.png"))); // NOI18N
        login_panel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 172, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Password");
        login_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 162, 122, 42));

        login_cancel_btn.setBackground(new java.awt.Color(255, 255, 255));
        login_cancel_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login_cancel_btn.setForeground(new java.awt.Color(40, 53, 147));
        login_cancel_btn.setText("Cancel");
        login_cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_cancel_btnActionPerformed(evt);
            }
        });
        login_panel.add(login_cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 242, 136, 65));

        user_password_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                user_password_txtKeyPressed(evt);
            }
        });
        login_panel.add(user_password_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 162, 183, 42));

        login_btn.setBackground(new java.awt.Color(255, 255, 255));
        login_btn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login_btn.setForeground(new java.awt.Color(40, 53, 147));
        login_btn.setText("login");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        login_btn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_btnKeyPressed(evt);
            }
        });
        login_panel.add(login_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 242, 136, 65));

        base_panel.add(login_panel, "card2");

        loading_panel.setBackground(new java.awt.Color(255, 255, 255));
        loading_panel.setPreferredSize(new java.awt.Dimension(64, 5));
        loading_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Loading DB.....");
        loading_panel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 64, 282, 93));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/image_1208871.gif"))); // NOI18N
        loading_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 164, -1, -1));

        base_panel.add(loading_panel, "card3");

        jPanel1.add(base_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 0, 440, 389));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_cancel_btnActionPerformed
         System.exit(0);
    }//GEN-LAST:event_login_cancel_btnActionPerformed

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        validateUser();  
    }//GEN-LAST:event_login_btnActionPerformed

    private void user_name_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_name_txtKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            user_password_txt.requestFocusInWindow();
        }
    }//GEN-LAST:event_user_name_txtKeyPressed

    private void user_password_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_user_password_txtKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            login_btn.requestFocusInWindow();
        }
    }//GEN-LAST:event_user_password_txtKeyPressed

    private void login_btnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_btnKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            validateUser();
        }
    }//GEN-LAST:event_login_btnKeyPressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splash().setVisible(true);
            }
        });
    }
    
           
    public void validateUser(){
        String userName = user_name_txt.getText();
        String password = String.valueOf(user_password_txt.getPassword());
        
        if(userName.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill the username and password form");
        }else{
            String real_password = connector.getRelavantRecord("users", "password", "user_name", userName);
            if(password.equals(real_password)){
//                ViewManipulation.changePanel(base_panel, loading_panel);                
//                new MainFrame().setVisible(true);
//                this.dispose();
               
               this.dispose();
               MainFrameInvokeTask mfit =new MainFrameInvokeTask();
               LoadingScreenInvokeTask lsit=new LoadingScreenInvokeTask();
               
               
               Thread tt = new Thread(mfit);
               Thread tt2=new Thread(lsit);
               tt.start();
               tt2.start();
               CheckMainFrameLiveTask cmflt=new CheckMainFrameLiveTask(tt, lsit,mfit);
              Thread tt3=new Thread(cmflt);
              tt3.start();
//                try {
//                   // tt.join();
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(Splash.class.getName()).log(Level.SEVERE, null, ex);
//                }
                
                System.out.println("dfghjk");
               
            }else{
                JOptionPane.showMessageDialog(null, "Check your usernmae and password");
            }
                
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel loading_panel;
    private javax.swing.JButton login_btn;
    private javax.swing.JButton login_cancel_btn;
    private javax.swing.JPanel login_panel;
    private javax.swing.JTextField user_name_txt;
    private javax.swing.JPasswordField user_password_txt;
    // End of variables declaration//GEN-END:variables
}
